version: "3.5"

services:
  diun:
    image: crazymax/diun:latest
    container_name: diun
    restart: unless-stopped
    volumes:
      - ./data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=$TZ
      - LOG_LEVEL=info
      - LOG_JSON=false
      - DIUN_WATCH_WORKERS=20
      - DIUN_WATCH_SCHEDULE=30 21 * * *
      - DIUN_WATCH_FIRSTCHECKNOTIF=false
      - DIUN_NOTIF_TELEGRAM_TOKEN=$TELEGRAM_TOKEN
      - DIUN_NOTIF_TELEGRAM_CHATIDS=$TELEGRAM_CHATIDS
      - DIUN_PROVIDERS_DOCKER=true
      - DIUN_PROVIDERS_DOCKER_WATCHBYDEFAULT=true
